---
version: '3'
services:
  frontend:
    image: patro30/frontend
    ports: 
      - 80:80
    depends_on: 
      - backend
    networks: 
      - server
  backend: 
    image: patro30/backend
    ports: 
      - 8080:8080
    depends_on: 
      - db
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3308/splitwisedb
      SPRING_DATASOURCE_USERNAME: bong
      SPRING_DATASOURCE_PASSWORD: password
    networks: 
      - server
      - database
  db: 
    image: mysql:8.0
    expose: 
      - 3308
    ports: 
      - 3308:3308
    environment: 
      MYSQL_DATABASE: splitwisedb
      MYSQL_USER: bong
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    networks: 
      - database
    volumes: 
      - dbstore:/var/lib/mysql
networks: 
  server: 
  database: 
volumes: 
  dbstore: 
